import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import RightSidebar from '../components/RightSidebar';
import Notifications from '../components/Notifications';
import DataVisualization from '../components/DataVisualization';
import { useState } from 'react';
import Feed from '../components/Feed';

export default function Home() {
  const { data: session } = useSession();
  const [showNotifications, setShowNotifications] = useState(false);
  const [showCharts, setShowCharts] = useState(false);
  const [showHome, setShowHome] = useState(true); // Added this line

  if (!session) return <Login />;

  return (
    <div>
      <Head> 
        <title>Tangled</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="flex min-h-screen">
        <Sidebar 
          onNotificationClick={() => {
            console.log("Notifications button clicked");
            setShowNotifications(!showNotifications);
            setShowCharts(false);
            setShowHome(false);
          }}
          onChartsClick={() => {
            console.log("Charts button clicked");
            setShowCharts(!showCharts);
            setShowNotifications(false);
            setShowHome(false);
          }}
          onHomeClick={() => {
            console.log("Home button clicked");
            setShowHome(true); // Changed to always set to true when home is clicked
            setShowNotifications(false);
            setShowCharts(false);
          }}  
        />
        
        {showNotifications && (
          <Notifications onClose={() => {
            console.log("Closing notifications");
            setShowNotifications(false);
            setShowHome(true); // Return to home when closing
          }} />
        )}
        
        {showCharts && (
          <DataVisualization onClose={() => {
            console.log("Closing charts");
            setShowCharts(false);
            setShowHome(true); // Return to home when closing
          }} />
        )}

        {showHome && <Feed />} {/* Removed onClose since home is the default view */}
        
        <RightSidebar />
      </main>
    </div>
  );
}